# Generated by Django 4.1.6 on 2023-02-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_users_alter_amis_user_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Profile',
        ),
    ]
