# Generated by Django 4.1.6 on 2023-02-17 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_amis_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amis',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
